# Generated by Django 5.1.4 on 2025-05-30 06:58

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='post_image',
            field=image_cropping.fields.ImageCropField(default=None, max_length=255, null=True, upload_to='blog/%Y/%m/%d', verbose_name='News Image (1280X720px)'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='video_thumbnail',
            field=image_cropping.fields.ImageCropField(blank=True, default='thumbnail/na.jpg', max_length=255, null=True, upload_to='thumbnail/%Y/%m/%d', verbose_name='Thumbnail (1280X720px)'),
        ),
    ]
