# Generated by Django 5.2.1 on 2025-10-18 09:18

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0002_alter_newspost_post_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='meta_title',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='Meta Title(35 to 65 chr standard)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, max_length=200, populate_from='meta_title', unique=True),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Status')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='newspost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post_management.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='videonews',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post_management.tag', verbose_name='Tags'),
        ),
    ]
